### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by AkiyamaCarson** [Yujia-Yan/Transkun#19]
Hello, I met with the problem that says "FileNotFoundError"

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-5-e60ecc137ce4>](https://localhost:8080/#) in <cell line: 22>()
     28 else:
     29     for fn in uploaded.keys():
---> 30       files.download(transcribe(fn, "."))

[/usr/local/lib/python3.10/dist-packages/google/colab/files.py](https://localhost:8080/#) in download(filename)
    223   if not _os.path.exists(filename):
    224     msg = 'Cannot find file: {}'.format(filename)
--> 225     raise FileNotFoundError(msg)  # pylint: disable=undefined-variable
    226 
    227   comm_manager = _IPython.get_ipython().kernel.comm_manager

**Comment by Yujia-Yan** [comment]
Fixed by adding the missing dependency. uploaded the new wheel to pypi.

**Comment by AkiyamaCarson** [comment]
That worked!
Thanks
