### ISSUE TITLE
Running transkun, it only says "Killed"

### ISSUE THREAD

**Issue by Dikakus** [Yujia-Yan/Transkun#9]
Hi, I was looking for a software for transcription and I found your page in github. I've installed it and ran:

transkun mp3_file.mp3 midi_file.mid

but the only result is the text "Killed" in the screen. Any suggestion to find the issue? 

Thank you!

**Comment by Yujia-Yan** [comment]
Most likely it's running out of memory.  
You can monitor the ram usage before "killed" or follow the steps in the link to find out the reason.
https://stackoverflow.com/questions/47408608/how-can-i-find-the-reason-that-python-script-is-killed

How much ram is there in your computer?
